# Generated by Django 5.0.1 on 2024-01-31 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('room_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Student Data',
                'verbose_name_plural': 'Student Data',
                'ordering': ('stud_id',),
            },
        ),
        migrations.CreateModel(
            name='CoreData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('breakfast', models.BooleanField(default=False)),
                ('lunch', models.BooleanField(default=False)),
                ('snack', models.BooleanField(default=False)),
                ('dinner', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'verbose_name': 'Core Data',
                'verbose_name_plural': 'Core Data',
                'ordering': ('id',),
            },
        ),
    ]
